### ISSUE TITLE
Error when reloading Config

### ISSUE THREAD

**Issue by rainbows123** [GC-spigot/battle-pass#11]
Hello! I get this error in console when I reload the plugin which seems to be something relating to Daily Quests even though they are set as disabled in the config. Thanks!

`[12:16:55 WARN]: Unexpected exception while parsing console command "bpa reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'bpa' in plugin BattlePass v3.13
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-Hyperion-9804b10]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[server.jar:git-Hyperion-9804b10]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[server.jar:git-Hyperion-9804b10]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629) [server.jar:git-Hyperion-9804b10]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:447) [server.jar:git-Hyperion-9804b10]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:411) [server.jar:git-Hyperion-9804b10]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [server.jar:git-Hyperion-9804b10]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [server.jar:git-Hyperion-9804b10]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NullPointerException
        at io.github.battlepass.quests.workers.reset.DailyQuestReset.stop(DailyQuestReset.java:86) ~[?:?]
        at io.github.battlepass.BattlePlugin.unload(BattlePlugin.java:314) ~[?:?]
        at io.github.battlepass.BattlePlugin.reload(BattlePlugin.java:239) ~[?:?]
        at io.github.battlepass.commands.bpadmin.ReloadSub.onExecute(ReloadSub.java:19) ~[?:?]
        at io.github.battlepass.simplespigot.command.command.Command.middleMan(Command.java:25) ~[?:?]
        at io.github.battlepass.simplespigot.command.CommandBase.onCommand(CommandBase.java:83) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Hyperion-9804b10]
        ... 8 more`

**Comment by GC-spigot** [comment]
Fixed!
