### ISSUE TITLE
[Issue] Error Critical error when starting the plugin

### ISSUE THREAD

**Issue by Futodama** [GC-spigot/battle-pass#138]
**Describe the bug**
[00:29:38 INFO]: [BattlePass] Enabling BattlePass v3.6.11
[00:29:38 INFO]: [BattlePass] Finished loading the daily quests. All quests loaded successfully.
[00:29:38 INFO]: [BattlePass] Finished loading the week-6 quests. All quests loaded successfully.
[00:29:38 INFO]: [BattlePass] Finished loading the week-1 quests. All quests loaded successfully.
[00:29:38 INFO]: [BattlePass] Finished loading the week-7 quests. All quests loaded successfully.
[00:29:38 INFO]: [BattlePass] Finished loading the week-2 quests. All quests loaded successfully.
[00:29:38 INFO]: [BattlePass] Finished loading the week-3 quests. All quests loaded successfully.
[00:29:38 INFO]: [BattlePass] Finished loading the week-5 quests. All quests loaded successfully.
[00:29:38 INFO]: [BattlePass] Finished loading the week-4 quests. All quests loaded successfully.
[00:29:38 ERROR]: Error occurred while enabling BattlePass v3.6.11 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "<local3>" is null
        at io.github.battlepass.cache.RewardCache.lambda$null$1(RewardCache.java:31) ~[battle-pass-3.6.11.jar:?]
        at io.github.battlepass.simplespigot.config.ConfigLoader$Reader.keyLoop(ConfigLoader.java:81) ~[battle-pass-3.6.11.jar:?]
        at io.github.battlepass.simplespigot.config.ConfigLoader$Reader.keyLoop(ConfigLoader.java:95) ~[battle-pass-3.6.11.jar:?]
        at io.github.battlepass.cache.RewardCache.lambda$cache$2(RewardCache.java:27) ~[battle-pass-3.6.11.jar:?]
        at io.github.battlepass.simplespigot.config.ConfigLoader$Reader.readWrap(ConfigLoader.java:25) ~[battle-pass-3.6.11.jar:?]
        at io.github.battlepass.cache.RewardCache.cache(RewardCache.java:26) ~[battle-pass-3.6.11.jar:?]
        at io.github.battlepass.BattlePlugin.load(BattlePlugin.java:277) ~[battle-pass-3.6.11.jar:?]
        at io.github.battlepass.BattlePlugin.onEnable(BattlePlugin.java:103) ~[battle-pass-3.6.11.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:305) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:263) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:389) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[paper-1.18.1.jar:git-Paper-182]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:860) ~[paper-1.18.1.jar:git-Paper-182]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:507) ~[paper-1.18.1.jar:git-Paper-182]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:481) ~[paper-1.18.1.jar:git-Paper-182]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-182]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-182]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-182]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:29:38 INFO]: [BattlePass] Disabling BattlePass v3.6.11

Discord ticket: https://discord.com/channels/376425582139015168/941098917792194574

**Server Information (please complete the following information):**
Paper version git-Paper-182 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 2ec04e0)
Plugin: BattlePass v3.6.11

**Comment by GC-spigot** [comment]
Your rewards are setup incorrectly. Next update the plugin will automatically report which reward is flawed.
