### ISSUE TITLE
[Issue] Battlepass does not start up

### ISSUE THREAD

**Issue by ConnorServers** [GC-spigot/battle-pass#199]
Hi,

I'm running on 1.12.2 GuardSpigot with Java 11.
I have tried the latest and last 4 versions of BattlePass with fresh configs and it does not load.

`[22:08:21 INFO]: [BattlePass] Hooked into AdvancedEnchantments
[22:08:21 INFO]: [BattlePass] Hooked into Citizens
[22:08:21 ERROR]: Error occurred while enabling BattlePass v3.10.0 (Is it up to date?)
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
        at io.github.battlepass.registry.quest.QuestRegistryImpl.entryToVersionNumber(QuestRegistryImpl.java:274) ~[?:?]
        at io.github.battlepass.registry.quest.QuestRegistryImpl.extractVersion(QuestRegistryImpl.java:258) ~[?:?]
        at io.github.battlepass.registry.quest.QuestRegistryImpl.hook(QuestRegistryImpl.java:192) ~[?:?]
        at io.github.battlepass.registry.quest.QuestRegistry.hook(QuestRegistry.java:77) ~[?:?]
        at io.github.battlepass.registry.quest.QuestRegistryImpl.register(QuestRegistryImpl.java:93) ~[?:?]
        at me.hyfe.simplespigot.plugin.SpigotPlugin.registerRegistries(SpigotPlugin.java:49) ~[?:?]
        at io.github.battlepass.BattlePlugin.load(BattlePlugin.java:285) ~[?:?]
        at io.github.battlepass.BattlePlugin.onEnable(BattlePlugin.java:97) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[server.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[server.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[server.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[server.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[server.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[server.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[server.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[server.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[server.jar:git-Paper-33d42c8e]
        at java.lang.Thread.run(Thread.java:829) [?:?]`

**Comment by GC-spigot** [comment]
Should be resolved
