### ISSUE TITLE
[Issue] Plugin disable when server start

### ISSUE THREAD

**Issue by iSeitan** [GC-spigot/battle-pass#253]
[14:23:40] [Server thread/INFO]: [BattlePass] Enabling BattlePass v3.13.1
[14:23:40] [Server thread/INFO]: [io.github.battlepass.hikari.HikariDataSource] battlePass-hikari - Starting...
[14:23:40] [Server thread/INFO]: [io.github.battlepass.hikari.HikariDataSource] battlePass-hikari - Start completed.
[14:23:40] [Server thread/INFO]: Successfully connected to MySQL.
[14:23:40] [Server thread/INFO]: [BattlePass] Finished loading the week-2 quests. All quests loaded successfully.
[14:23:40] [Server thread/INFO]: [BattlePass] Finished loading the week-1 quests. All quests loaded successfully.
[14:23:40] [Server thread/INFO]: [BattlePass] Finished loading the week-3 quests. All quests loaded successfully.
[14:23:40] [Server thread/INFO]: [BattlePass] Finished loading the week-4 quests. All quests loaded successfully.
[14:23:40] [Server thread/INFO]: [BattlePass] Finished loading the daily quests. All quests loaded successfully.
[14:23:40] [Server thread/ERROR]: Error occurred while enabling BattlePass v3.13.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.Set.iterator()" because the return value of "me.hyfe.simplespigot.config.Config.keys(String, boolean)" is null
	at me.hyfe.simplespigot.config.ConfigLoader$Reader.keyLoop(ConfigLoader.java:79) ~[battle-pass-3.13.1.jar:?]
	at me.hyfe.simplespigot.config.ConfigLoader$Reader.keyLoop(ConfigLoader.java:87) ~[battle-pass-3.13.1.jar:?]
	at io.github.battlepass.cache.RewardCache.lambda$cache$1(RewardCache.java:38) ~[battle-pass-3.13.1.jar:?]
	at me.hyfe.simplespigot.config.ConfigLoader$Reader.keyLoop(ConfigLoader.java:81) ~[battle-pass-3.13.1.jar:?]
	at me.hyfe.simplespigot.config.ConfigLoader$Reader.keyLoop(ConfigLoader.java:95) ~[battle-pass-3.13.1.jar:?]
	at io.github.battlepass.cache.RewardCache.lambda$cache$2(RewardCache.java:27) ~[battle-pass-3.13.1.jar:?]
	at me.hyfe.simplespigot.config.ConfigLoader$Reader.readWrap(ConfigLoader.java:25) ~[battle-pass-3.13.1.jar:?]
	at io.github.battlepass.cache.RewardCache.cache(RewardCache.java:26) ~[battle-pass-3.13.1.jar:?]
	at io.github.battlepass.BattlePlugin.load(BattlePlugin.java:271) ~[battle-pass-3.13.1.jar:?]
	at io.github.battlepass.BattlePlugin.onEnable(BattlePlugin.java:98) ~[battle-pass-3.13.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-338]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-338]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-338]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-338]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-338]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-338]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-338]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:23:40] [Server thread/INFO]: [BattlePass] Disabling BattlePass v3.13.1
[14:23:40] [Server thread/ERROR]: Error occurred while disabling BattlePass v3.13.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "io.github.battlepass.quests.workers.reset.DailyQuestReset.getCurrentQuests()" because "<parameter1>" is null
	at io.github.battlepass.storage.DailyQuestStorage.lambda$serializer$2(DailyQuestStorage.java:33) ~[battle-pass-3.13.1.jar:?]
	at me.hyfe.simplespigot.storage.storage.Storage.save(Storage.java:50) ~[battle-pass-3.13.1.jar:?]
	at io.github.battlepass.BattlePlugin.unload(BattlePlugin.java:322) ~[battle-pass-3.13.1.jar:?]
	at io.github.battlepass.BattlePlugin.onDisable(BattlePlugin.java:110) ~[battle-pass-3.13.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:400) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:581) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:375) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-338]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-338]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-338]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-338]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-338]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-338]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-338]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Server Information (please complete the following information):**
paper-1.19.3-338
battle-pass-3.13.1

**Comment by GC-spigot** [comment]
Fixed
