### ISSUE TITLE
[Issue]: ERROR CONSOLE EXCELLENTCRATES

### ISSUE THREAD

**Issue by tomimza** [GC-spigot/battle-pass#258]
**Describe the bug**
In open a crate, send console

**To Reproduce**
[13:02:57 ERROR]: Could not pass event CrateOpenEvent to BattlePass v3.13.7
java.lang.NoSuchMethodError: 'su.nightexpress.excellentcrates.api.crate.ICrate su.nightexpress.excellentcrates.api.event.CrateOpenEvent.getCrate()'
        at io.github.battlepass.quests.quests.external.ExcellentCratesQuest.onCrateOpen(ExcellentCratesQuest.java:19) ~[battle-pass-3.13.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1403.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-light-"aaf5e39"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at su.nightexpress.excellentcrates.crate.CrateManager.openCrate(CrateManager.java:282) ~[ExcellentCrates-4.1.5.jar:?]
        at su.nightexpress.excellentcrates.crate.CrateManager.interactCrate(CrateManager.java:211) ~[ExcellentCrates-4.1.5.jar:?]
        at su.nightexpress.excellentcrates.crate.CrateListener.onCrateUse(CrateListener.java:68) ~[ExcellentCrates-4.1.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor585.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-light-"aaf5e39"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:527) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1972) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1353) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:188) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1330) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1323) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1301) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1189) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:308) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Screenshots / Video**
None.

**Server Information (please complete the following information):**
- Server Version: [e.g. LightSpigot 1.19.2]
- Plugin Version: [battle-pass-3.13.7]

**Comment by cRestalious** [comment]
Same issue
