### ISSUE TITLE
I met an error when i try to break a block

### ISSUE THREAD

**Issue by VincentVVV2016** [GC-spigot/battle-pass#309]
### Describe the bug

A block of a rendered model made from CustomBlocksMod
[02:35:04] [Server thread/ERROR]: Could not pass event BlockBreakEvent to BattlePass v3.15.5
java.lang.NoClassDefFoundError: org/bukkit/Tag
at io.github.battlepass.quests.quests.internal.HarvestCropsQuest.onHarvest(HarvestCropsQuest.java:22) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1017.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PAPER.jar:git-Paper-1618]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PAPER.jar:git-Paper-1618]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PAPER.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[PAPER.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:322) ~[PAPER.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:124) ~[PAPER.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:934) ~[PAPER.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[PAPER.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[PAPER.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PAPER.jar:git-Paper-1618]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_361]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_361]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[PAPER.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[PAPER.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[PAPER.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[PAPER.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[PAPER.jar:git-Paper-1618]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_361]

### How to reproduce

I met an error when i try to break a block
A block of a rendered model made from CustomBlocksMod

**Comment by GC-spigot** [comment]
Fixed
