### ISSUE TITLE
Latest version has 1.12 errors

### ISSUE THREAD

**Issue by SladeHazard** [GC-spigot/battle-pass#311]
### Describe the bug

server spams error on 1.12 

### How to reproduce

break blocks

### Screenshots / Videos

 [17:48:16 ERROR]: Could not pass event BlockBreakEvent to BattlePass v3.15.7
java.lang.NoSuchMethodError: org.bukkit.block.Block.getBlockData()Lorg/bukkit/block/data/BlockData;
        at io.github.battlepass.quests.quests.internal.HarvestCropsQuest.onHarvest(HarvestCropsQuest.java:28) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1496.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(:70) ~[server.jar:git-Paper-2116373]
        at co.aikar.timings.TimedEventExecutor.execute(:74) ~[server.jar:git-Paper-2116373]
        at org.bukkit.plugin.RegisteredListener.callEvent(:62) ~[server.jar:git-Paper-2116373]
        at org.bukkit.plugin.SimplePluginManager.callEvent(:513) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(:322) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(:193) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(:942) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(:40) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(:10) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(:14) ~[server.jar:git-Paper-2116373]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(:46) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(:854) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(:431) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(:778) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(:669) ~[server.jar:git-Paper-2116373]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by GC-spigot** [comment]
Fixed! Sorry about delays
