### ISSUE TITLE
[15:11:36 WARN]: [BattlePass] Task #2326768 for BattlePass v3.16.3 generated an exception

### ISSUE THREAD

**Issue by AVuTuVA** [GC-spigot/battle-pass#320]
### Describe the bug

error

### How to reproduce

.

### Screenshots / Videos

[15:11:36 WARN]: [BattlePass] Task #2326768 for BattlePass v3.16.3 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.persistence.PersistentDataContainer org.bukkit.inventory.meta.ItemMeta.getPersistentDataContainer()'
        at io.github.battlepass.quests.quests.internal.BrewingQuest.lambda$on$0(BrewingQuest.java:50) ~[?:?]
        at java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[?:?]
        at io.github.battlepass.quests.quests.internal.BrewingQuest.lambda$on$1(BrewingQuest.java:44) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[core.jar:git-Paper-4466fe0]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[core.jar:git-Paper-4466fe0]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:859) ~[core.jar:git-Paper-4466fe0]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[core.jar:git-Paper-4466fe0]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:793) ~[core.jar:git-Paper-4466fe0]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:683) ~[core.jar:git-Paper-4466fe0]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by AVuTuVA** [comment]
![image](https://user-images.githubusercontent.com/66278054/230921529-99d62291-8d07-410d-b48c-341f701d0fc7.png)
