### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent & PlayerMoveEvent to BattlePass v3.16.8

### ISSUE THREAD

**Issue by Dominiiikk** [GC-spigot/battle-pass#331]
### Describe the bug

After updating battlepass from v3.15.3 to the latest one (v3.16.8) it started to spam console with these  2errors:

```
12:30:38[ERROR] Could not pass event AsyncPlayerChatEvent to BattlePass v3.16.8
java.lang.IllegalStateException: UserQuestProgressionEvent may only be triggered synchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:666) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.proceed(QuestValidationStep.java:109) ~[BattlePass-3.16.8.jar:?]
at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.processCompletion(QuestValidationStep.java:88) ~[BattlePass-3.16.8.jar:?]
at io.github.battlepass.quests.workers.pipeline.QuestPipeline.handle(QuestPipeline.java:47) ~[BattlePass-3.16.8.jar:?]
at io.github.battlepass.quests.service.executor.QuestExecutionBuilderImpl.buildAndExecute(QuestExecutionBuilderImpl.java:34) ~[BattlePass-3.16.8.jar:?]
at io.github.battlepass.quests.quests.internal.ChatQuest.onPlayerChat(ChatQuest.java:34) ~[BattlePass-3.16.8.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor751.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:381) ~[purpur-1.19.2.jar:git-Purpur-1858]
at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:96) ~[purpur-1.19.2.jar:git-Purpur-1858]
at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2496) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:130) ~[InteractiveChat-4.2.6.0.jar:?]
at com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$4(RedispatchSignedPacket.java:92) ~[InteractiveChat-4.2.6.0.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1858]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
```

```
[13:39:04] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to BattlePass v3.16.8
java.lang.NullPointerException: Cannot invoke "io.github.battlepass.objects.user.User.getQuestStore()" because "<parameter1>" is null
	at io.github.battlepass.controller.QuestController.lambda$new$0(QuestController.java:16) ~[BattlePass-3.16.8.jar:?]
	at io.github.battlepass.controller.QuestController.failedIndex(QuestController.java:101) ~[BattlePass-3.16.8.jar:?]
	at io.github.battlepass.controller.QuestController.getQuestProgress(QuestController.java:55) ~[BattlePass-3.16.8.jar:?]
	at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.proceed(QuestValidationStep.java:96) ~[BattlePass-3.16.8.jar:?]
	at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.processCompletion(QuestValidationStep.java:88) ~[BattlePass-3.16.8.jar:?]
	at io.github.battlepass.quests.workers.pipeline.QuestPipeline.handle(QuestPipeline.java:47) ~[BattlePass-3.16.8.jar:?]
	at io.github.battlepass.quests.service.executor.QuestExecutionBuilderImpl.buildAndExecute(QuestExecutionBuilderImpl.java:34) ~[BattlePass-3.16.8.jar:?]
	at io.github.battlepass.quests.quests.internal.MovementQuests.onMove(MovementQuests.java:28) ~[BattlePass-3.16.8.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor770.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1674) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

### How to reproduce

Download the latest version on server and start.

### Server Log

Its too big for the paste site, waited long for upload, but it wont happed. Tried uploading the file on my drive: https://drive.google.com/file/d/1svRzl-8coUQ2h1ELy8nnMmwn2OO_BRyy/view?usp=sharing

**Comment by Dominiiikk** [comment]
Any updates? Info? Something? I've been said on discord, that you'll look at it ASAP, if i open the issue here.
Our players aren't happy, that they cannot coplete some quests. And spammed-out console isn't great too.

**Comment by Dominiiikk** [comment]
It looks like that only the AsyncPlayerChatEvent remains. (And CrateOpenEvent, which i understand why)

```
10:53:21[ERROR] Could not pass event AsyncPlayerChatEvent to BattlePass v3.16.8
java.lang.IllegalStateException: UserQuestProgressionEvent may only be triggered synchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:666) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.proceed(QuestValidationStep.java:109) ~[BattlePass-3.16.8.jar:?]
at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.processCompletion(QuestValidationStep.java:88) ~[BattlePass-3.16.8.jar:?]
at io.github.battlepass.quests.workers.pipeline.QuestPipeline.handle(QuestPipeline.java:47) ~[BattlePass-3.16.8.jar:?]
at io.github.battlepass.quests.service.executor.QuestExecutionBuilderImpl.buildAndExecute(QuestExecutionBuilderImpl.java:34) ~[BattlePass-3.16.8.jar:?]
at io.github.battlepass.quests.quests.internal.ChatQuest.onPlayerChat(ChatQuest.java:34) ~[BattlePass-3.16.8.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor751.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:381) ~[purpur-1.19.2.jar:git-Purpur-1858]
at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:96) ~[purpur-1.19.2.jar:git-Purpur-1858]
at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2496) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor152.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:130) ~[InteractiveChat-4.2.6.0.jar:?]
at com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$4(RedispatchSignedPacket.java:92) ~[InteractiveChat-4.2.6.0.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1858]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
```
