### ISSUE TITLE
An error 

### ISSUE THREAD

**Issue by VincentVVV2016** [GC-spigot/battle-pass#336]
### Describe the bug

[20:41:15 WARN]: [BattlePass] Task #424 for BattlePass v3.16.8 generated an exception
java.lang.NullPointerException: null
        at io.github.battlepass.controller.QuestController.lambda$new$0(QuestController.java:16) ~[?:?]
        at io.github.battlepass.controller.QuestController.failedIndex(QuestController.java:101) ~[?:?]
        at io.github.battlepass.controller.QuestController.getQuestProgress(QuestController.java:55) ~[?:?]
        at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.proceed(QuestValidationStep.java:96) ~[?:?]
        at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.processCompletion(QuestValidationStep.java:88) ~[?:?]
        at io.github.battlepass.quests.workers.pipeline.QuestPipeline.handle(QuestPipeline.java:47) ~[?:?]
        at io.github.battlepass.quests.service.executor.QuestExecutionBuilderImpl.buildAndExecute(QuestExecutionBuilderImpl.java:34) ~[?:?]
        at io.github.battlepass.quests.quests.external.executor.ExternalQuestExecutor.execute(ExternalQuestExecutor.java:53) ~[?:?]
        at io.github.battlepass.quests.quests.external.PlaceholderApiQuests.lambda$placeholderRun$2(PlaceholderApiQuests.java:57) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[PAPER.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[PAPER.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_361]

### How to reproduce

Join the server

**Comment by VincentVVV2016** [comment]
Hello author, thank you for your reply. This error is probabilistic and may only occur once after joining the server 10 times
And I have carefully reviewed all the complete logs, only this section reported an error, and there is nothing else


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GC-spigot/battle-pass"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 晚上10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GC-spigot/battle-pass] An error  (Issue #336)





 
Always include a server log, this is impossible for me to recreate. Also your battlepass configuration will be needed

**Comment by GC-spigot** [comment]
The reason I need log is to see the sequence of events happening before this error, other plugin loading sequence etc. Without it, it's impossible for me to fix this.
