### ISSUE TITLE
NoPlayerOnline Exception

### ISSUE THREAD

**Issue by jtJava** [GC-spigot/battle-pass#340]
### Describe the bug

[23:20:40 INFO]: Iowa lost connection: Disconnected
[23:20:40 WARN]: [NoEncryption] Could not remove the server packet handler for Iowa (d50a7e87-2082-4956-8ffb-094f26a9af1e)
[23:20:40 WARN]: [NoEncryption] This is not a fatal error, will be cleaned in garbage collection, and can be safely ignored
[23:20:40 WARN]: [Analyse] Failed to track player session for Iowa.
[23:20:40 INFO]: [org.mongodb.driver.connection] Opened connection [connectionId{localValue:30, serverValue:983}] to 172.18.0.1:27017
[23:20:40 WARN]: [BattlePass] Task #5087 for BattlePass v3.17.1 generated an exception
io.github.battlepass.exceptions.NoOnlineUserException: Could not find an online user with the uuid d50a7e87-2082-4956-8ffb-094f26a9af1e
        at io.github.battlepass.cache.UserCache.getOrThrow(UserCache.java:39) ~[BattlePass-3.17.1.jar:?]
        at io.github.battlepass.quests.workers.pipeline.QuestPipeline.handle(QuestPipeline.java:45) ~[BattlePass-3.17.1.jar:?]
        at io.github.battlepass.quests.service.executor.QuestExecutionBuilderImpl.buildAndExecute(QuestExecutionBuilderImpl.java:34) ~[BattlePass-3.17.1.jar:?]
        at io.github.battlepass.quests.quests.internal.LoginQuest.lambda$onJoin$0(LoginQuest.java:30) ~[BattlePass-3.17.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]

### How to reproduce

relog

**Comment by jtJava** [comment]
[03:07:50 INFO]: Iowa[/69.57.196.56:43528] logged in with entity id 115 at ([world]-9.5, 53.0, -51.5)
[03:07:51 ERROR]: Could not pass event PlayerMoveEvent to BattlePass v3.17.1
java.lang.NullPointerException: Cannot invoke "io.github.battlepass.objects.user.User.getQuestStore()" because "user" is null
        at io.github.battlepass.controller.QuestController.lambda$new$0(QuestController.java:16) ~[BattlePass-3.17.1.jar:?]
        at io.github.battlepass.controller.QuestController.failedIndex(QuestController.java:101) ~[BattlePass-3.17.1.jar:?]
        at io.github.battlepass.controller.QuestController.getQuestProgress(QuestController.java:55) ~[BattlePass-3.17.1.jar:?]
        at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.proceed(QuestValidationStep.java:96) ~[BattlePass-3.17.1.jar:?]
        at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.processCompletion(QuestValidationStep.java:88) ~[BattlePass-3.17.1.jar:?]
        at io.github.battlepass.quests.workers.pipeline.QuestPipeline.handle(QuestPipeline.java:47) ~[BattlePass-3.17.1.jar:?]
        at io.github.battlepass.quests.service.executor.QuestExecutionBuilderImpl.buildAndExecute(QuestExecutionBuilderImpl.java:34) ~[BattlePass-3.17.1.jar:?]
        at io.github.battlepass.quests.quests.internal.MovementQuests.onMove(MovementQuests.java:28) ~[BattlePass-3.17.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor82.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-448]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1593) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by jtJava** [comment]
I think these errors are related to me having BungeeFix set to true

**Comment by GC-spigot** [comment]
Should be resolved next update
