### ISSUE TITLE
Exception in chat when joining

### ISSUE THREAD

**Issue by jtJava** [GC-spigot/battle-pass#349]
### Describe the bug

[03:57:03 WARN]: [BattlePass] Task #319 for BattlePass v3.17.4 generated an exception
java.lang.NullPointerException: Cannot invoke "io.github.battlepass.objects.user.User.getQuestStore()" because "user" is null
        at io.github.battlepass.controller.QuestController.lambda$new$0(QuestController.java:16) ~[BattlePass-3.17.4.jar:?]
        at io.github.battlepass.controller.QuestController.failedIndex(QuestController.java:101) ~[BattlePass-3.17.4.jar:?]
        at io.github.battlepass.controller.QuestController.getQuestProgress(QuestController.java:55) ~[BattlePass-3.17.4.jar:?]
        at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.proceed(QuestValidationStep.java:96) ~[BattlePass-3.17.4.jar:?]
        at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.processCompletion(QuestValidationStep.java:88) ~[BattlePass-3.17.4.jar:?]
        at io.github.battlepass.quests.workers.pipeline.QuestPipeline.handle(QuestPipeline.java:51) ~[BattlePass-3.17.4.jar:?]
        at io.github.battlepass.quests.service.executor.QuestExecutionBuilderImpl.buildAndExecute(QuestExecutionBuilderImpl.java:34) ~[BattlePass-3.17.4.jar:?]
        at io.github.battlepass.quests.quests.internal.PlayTimeQuest.lambda$run$0(PlayTimeQuest.java:21) ~[BattlePass-3.17.4.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

Use the mysql delayed load option in the config.

### Screenshots / Videos

![image](https://github.com/GC-spigot/battle-pass/assets/37258614/7ff90936-f651-4b37-8e3b-92d8d54f6fc5)

**Comment by jtJava** [comment]
This is nearly every time after joining the server, should be super simple to fix.

**Comment by jtJava** [comment]
Any update? It's very spammy

**Comment by valeriorobert** [comment]
I have the same issue, very spammy in consol with every player that joins. 
I have 1.19.4 paper, Battlepass, and Plotsquared latest version.
I m using json to store data.

**Comment by jtJava** [comment]
Still waiting on fix using 3.17.6

**Comment by SlimeCody** [comment]
We started running into this issue when we began running 3.17.8

**Comment by jtJava** [comment]
https://github.com/GC-spigot/battle-pass/issues/365

I believe this is related to the fix.
