### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by bobhenl** [GC-spigot/battle-pass#360]
### Describe the bug

Hello, I'm receiving this Battlepass error spam regularly:
`
[09:28:01] [Server thread/WARN]: [BattlePass] Task #1336699 for BattlePass v3.17.7 generated an exception
java.lang.NullPointerException: Cannot invoke "io.github.battlepass.objects.user.User.getQuestStore()" because "<parameter1>" is null
	at io.github.battlepass.controller.QuestController.lambda$new$0(QuestController.java:16) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.controller.QuestController.failedIndex(QuestController.java:101) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.controller.QuestController.getQuestProgress(QuestController.java:55) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.proceed(QuestValidationStep.java:96) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.processCompletion(QuestValidationStep.java:88) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.quests.workers.pipeline.QuestPipeline.handle(QuestPipeline.java:51) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.quests.service.executor.QuestExecutionBuilderImpl.buildAndExecute(QuestExecutionBuilderImpl.java:34) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.quests.quests.internal.LoginQuest.lambda$onJoin$0(LoginQuest.java:30) ~[BattlePass-3.17.7.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

`
[09:28:09] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to BattlePass v3.17.7
java.lang.NullPointerException: Cannot invoke "io.github.battlepass.objects.user.User.getQuestStore()" because "<parameter1>" is null
	at io.github.battlepass.controller.QuestController.lambda$new$0(QuestController.java:16) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.controller.QuestController.failedIndex(QuestController.java:101) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.controller.QuestController.getQuestProgress(QuestController.java:55) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.proceed(QuestValidationStep.java:96) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.processCompletion(QuestValidationStep.java:88) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.quests.workers.pipeline.QuestPipeline.handle(QuestPipeline.java:51) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.quests.service.executor.QuestExecutionBuilderImpl.buildAndExecute(QuestExecutionBuilderImpl.java:34) ~[BattlePass-3.17.7.jar:?]
	at io.github.battlepass.quests.quests.internal.MovementQuests.onMove(MovementQuests.java:32) ~[BattlePass-3.17.7.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1696.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1985]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1674) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:88) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
`
[Log.log](https://github.com/GC-spigot/battle-pass/files/11790389/Log.log)
Log snippet

### How to reproduce

Not really sure unfortunately, may you have an ieda when you see the log.

### Server Log

Cannot upload here, unfortunately even snippet is so big, check the file above

**Comment by GC-spigot** [comment]
Should be resolved!
