### ISSUE TITLE
StrikePractice bug

### ISSUE THREAD

**Issue by Darth17Skrill** [GC-spigot/battle-pass#413]
### Describe the bug

When the duel vs another player start BattlePass give me an error.
This bug is only vs another player, and not vs a bot.
Server version: 1.8 (Spigot)
Plugins: 
- StrikePractice (latest ver.)
- BattlePass (latest ver.)

### How to reproduce

When the duel vs another player start BattlePass give me an error.
This bug is only vs another player, and not vs a bot.
Server version: 1.8 (Spigot)
Plugins: 
- StrikePractice (latest ver.)
- BattlePass (latest ver.)

### Screenshots / Videos

[14:26:48 ERROR]: Could not pass event DuelStartEvent to BattlePass v4.0.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at ga.strikepractice.fights.duel.Duel.handleStart(Duel.java:100) ~[?:?]
        at ga.strikepractice.fights.duel.Duel.<init>(Duel.java:82) ~[?:?]
        at ga.strikepractice.fights.queue.d.b(QueueManager.kt:264) ~[?:?]
        at ga.strikepractice.fights.queue.d.a(QueueManager.kt:227) ~[?:?]
        at ga.strikepractice.fights.queue.d.onCommand(QueueManager.kt:70) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1078) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:237) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at me.filoghost.chestcommands.action.PlayerCommandAction.execute(PlayerCommandAction.java:21) ~[?:?]
        at me.filoghost.chestcommands.icon.InternalConfigurableIcon.onClickGetResult(InternalConfigurableIcon.java:156) ~[?:?]
        at me.filoghost.chestcommands.icon.InternalConfigurableIcon.onClick(InternalConfigurableIcon.java:119) ~[?:?]
        at me.filoghost.chestcommands.listener.InventoryListener.lambda$onLateInventoryClick$0(InventoryListener.java:84) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
Caused by: java.lang.NullPointerException
        at net.advancedplugins.bp.impl.actions.external.StrikePracticeQuests.onDuelStart(StrikePracticeQuests.java:65) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        ... 25 more

**Comment by Erdi-GitHub** [comment]
This should be fixed in the next update!
