### ISSUE TITLE
ERROR Minecraft] Could not pass event PlayerInteractEvent to BattlePass v4.0.5

### ISSUE THREAD

**Issue by Darth17Skrill** [GC-spigot/battle-pass#417]
### Describe the bug

With the newest versions when a player hit a block (left or right click) the console report an error.

### How to reproduce

Spigot version: 1.8.8
Java: 8

### Screenshots / Videos

- [mer 22:09:31 ERROR Minecraft] Could not pass event PlayerInteractEvent to BattlePass v4.0.5
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228)
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195)
    at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107)
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623)
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40)
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10)
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
    at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Block.getBlockData()Lorg/bukkit/block/data/BlockData;
    at net.advancedplugins.bp.impl.actions.objects.variable.ExecutableActionResult.root(ExecutableActionResult.java:42)
    at net.advancedplugins.bp.impl.actions.ActionExecutionBuilder.root(ActionExecutionBuilder.java:99)
    at net.advancedplugins.bp.impl.actions.inte

**Comment by Erdi-GitHub** [comment]
Fixed - the patch will be included in the next update
