### ISSUE TITLE
An ERROR With Version 4.0.5

### ISSUE THREAD

**Issue by VincentVVV2016** [GC-spigot/battle-pass#419]
### Describe the bug

**Minecraft Version : PaperSpigot 1.12.2**
**

One of my plugins places and displays the model by assigning NBT to the skull object. When I try to interact with and destroy the skull model, an Error will appear

**
`[06:23:55 ERROR]: Could not pass event PlayerInteractEvent to BattlePass v4.0.5
java.lang.NoSuchMethodError: org.bukkit.block.Block.getBlockData()Lorg/bukkit/block/data/BlockData;
        at net.advancedplugins.bp.impl.actions.objects.variable.ExecutableActionResult.root(ExecutableActionResult.java:42) ~[?:?]
        at net.advancedplugins.bp.impl.actions.ActionExecutionBuilder.root(ActionExecutionBuilder.java:99) ~[?:?]
        at net.advancedplugins.bp.impl.actions.internal.ClickQuest.onPlayerInteract(ClickQuest.java:48) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor852.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PAPER.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PAPER.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PAPER.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[PAPER.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[PAPER.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:203) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:109) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:934) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PAPER.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_361]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_361]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[PAPER.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_361]`

`[06:22:02 ERROR]: Could not pass event BlockBreakEvent to BattlePass v4.0.5
java.lang.NoSuchMethodError: org.bukkit.block.Block.getBlockData()Lorg/bukkit/block/data/BlockData;
        at net.advancedplugins.bp.impl.actions.objects.variable.ExecutableActionResult.root(ExecutableActionResult.java:42) ~[?:?]
        at net.advancedplugins.bp.impl.actions.ActionExecutionBuilder.root(ActionExecutionBuilder.java:99) ~[?:?]
        at net.advancedplugins.bp.impl.actions.internal.BlockBreakAction.onBlockBreak(BlockBreakAction.java:38) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor848.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PAPER.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PAPER.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PAPER.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:322) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:221) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:948) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PAPER.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_361]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_361]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[PAPER.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[PAPER.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_361]`

### How to reproduce

One of my plugins places and displays the model by assigning NBT to the skull object. When I try to interact with and destroy the skull model, an Error will appear

### Screenshots / Videos

![image](https://github.com/GC-spigot/battle-pass/assets/20635875/d5509d8f-083b-46a5-a957-3d8a165f4e62)
![image](https://github.com/GC-spigot/battle-pass/assets/20635875/c492a66b-1fad-4e6c-9499-cfa9b6483cac)

### Server Log

https://mcpaste.io/4aef973d6bfbe7b8

**Comment by Erdi-GitHub** [comment]
This was fixed in 4.0.6
