### ISSUE TITLE
CraftItem Event bug on 1.8.8

### ISSUE THREAD

**Issue by BigLionOG** [GC-spigot/battle-pass#451]
### Describe the bug

[20:04:27 ERROR]: Could not pass event CraftItemEvent to BattlePass v4.0.16
java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getStorageContents()[Lorg/bukkit/inventory/ItemStack;
        at net.advancedplugins.bp.impl.actions.internal.CraftQuest.getCraftedAmount(CraftQuest.java:67) ~[?:?]
        at net.advancedplugins.bp.impl.actions.internal.CraftQuest.onCraftItem(CraftQuest.java:31) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor580.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:64) ~[server.jar:1_8_R3]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:1_8_R3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:1_8_R3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:537) ~[server.jar:1_8_R3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:2007) ~[server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:17) ~[server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:5) ~[server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[server.jar:1_8_R3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:11) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:977) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:371) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:897) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:782) [server.jar:1_8_R3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

### How to reproduce

It randomly happens. Could not find a correlation.

**Comment by BigLionOG** [comment]
And this bug:
[01:17:16 ERROR]: Could not pass event BlockPistonExtendEvent to BattlePass v4.0.16
java.lang.NoSuchMethodError: org.bukkit.block.BlockFace.getDirection()Lorg/bukkit/util/Vector;
        at net.advancedplugins.bp.impl.actions.internal.BlockPlaceQuest.onPiston(BlockPlaceQuest.java:57) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor573.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:64) ~[server.jar:1_8_R3]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:1_8_R3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:1_8_R3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:537) [server.jar:1_8_R3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:516) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.BlockPiston.a(BlockPiston.java:396) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.BlockPiston.a(BlockPiston.java:141) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:1517) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.WorldServer.ak(WorldServer.java:1503) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:315) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1075) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:371) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:897) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:782) [server.jar:1_8_R3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by GC-spigot** [comment]
Hi! We'll be dropping support for 1.8 - 1.13 very soon. We have a handful of 1.8 servers using this plugin out of 1500+ servers, and it's clearly now causing issues having support for all versions, cannot keep support for 9+ year old version, it's time to move on.

This error comes from missing features on 1.8 which we cannot add or have backwards compatibility.
