### ISSUE TITLE
Daily Quest Mysql

### ISSUE THREAD

**Issue by xPoyraz** [GC-spigot/battle-pass#469]
### Describe the feature

Can you save daily tasks in the database?
My servers are cross server, I use battlepass on more than one server connected to the same database, but the daily tasks are different on each server because the daily tasks are not saved in the database.

**Comment by Timoti11** [comment]
up, me too

**Comment by xPoyraz** [comment]
```
[BattlePass] Plugin BattlePass v4.1.8 generated an exception while executing task 1109436
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'c0599899-dafc-39cf-b8b8-57c260a6bdd6' for key 'PRIMARY'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118) ~[mysql-connector-j-8.2.0.jar:8.2.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.2.0.jar:8.2.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912) ~[mysql-connector-j-8.2.0.jar:8.2.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354) ~[mysql-connector-j-8.2.0.jar:8.2.0]
	at io.github.battlepass.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[BattlePass-4.1.8.jar:?]
	at io.github.battlepass.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[BattlePass-4.1.8.jar:?]
	at me.hyfe.simplespigot.storage.backends.mysql.MySqlBackend.save(MySqlBackend.java:63) ~[BattlePass-4.1.8.jar:?]
	at me.hyfe.simplespigot.storage.storage.Storage.save(Storage.java:50) ~[BattlePass-4.1.8.jar:?]
	at io.github.battlepass.cache.UserCache.lambda$save$6(UserCache.java:122) ~[BattlePass-4.1.8.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2110]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2110]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
```

In fact, it's strange that the only "Battle Pass" add-on developed since 2018 doesn't support them.When 2 servers use the same database, I think the data is copied and such an error comes

**Of course, these elaborations are not a must, but I was a little disappointed**

**Comment by EponAAAADDD** [comment]
have opened a ticket on Discord. According to the staff, this is not a bug. If want it you must submit a feature request on GitHub
