### ISSUE TITLE
Console database error

### ISSUE THREAD

**Issue by EagL3-GIT** [GC-spigot/battle-pass#487]
### Describe the bug

:48:57 WARN]: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: battlepasshikari - Connection is not available, request timed out after 5000ms.
[15:48:57 WARN]: at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[15:48:57 WARN]: at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[15:48:57 WARN]: at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
[15:48:57 WARN]: at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[15:48:57 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:48:57 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:48:57 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[15:48:57 WARN]: Caused by: java.sql.SQLTransientConnectionException: battlepasshikari - Connection is not available, request timed out after 5000ms.
[15:48:57 WARN]: at BattlePass-4.2.8.jar//io.github.battlepass.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
[15:48:57 WARN]: at BattlePass-4.2.8.jar//io.github.battlepass.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[15:48:57 WARN]: at BattlePass-4.2.8.jar//io.github.battlepass.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[15:48:57 WARN]: at BattlePass-4.2.8.jar//io.github.battlepass.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[15:48:57 WARN]: at BattlePass-4.2.8.jar//me.hyfe.simplespigot.storage.backends.mysql.MySqlConnectionFactory.getConnection(MySqlConnectionFactory.java:38)
[15:48:57 WARN]: at BattlePass-4.2.8.jar//me.hyfe.simplespigot.storage.backends.mysql.MySqlBackend.load(MySqlBackend.java:40)
[15:48:57 WARN]: at BattlePass-4.2.8.jar//me.hyfe.simplespigot.storage.storage.Storage.load(Storage.java:47)
[15:48:57 WARN]: at BattlePass-4.2.8.jar//io.github.battlepass.cache.UserCache.lambda$load$1(UserCache.java:61)
[15:48:57 WARN]: at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[15:48:57 WARN]: ... 4 more
[15:48:57 WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "io.github.battlepass.objects.user.User.getPendingTiers(String)" because "<parameter1>" is null
[15:48:57 WARN]: at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[15:48:57 WARN]: at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[15:48:57 WARN]: at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
[15:48:57 WARN]: at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[15:48:57 WARN]: at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
[15:48:57 WARN]: at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:653)
[15:48:57 WARN]: at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[15:48:57 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:48:57 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:48:57 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[15:48:57 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "io.github.battlepass.objects.user.User.getPendingTiers(String)" because "<parameter1>" is null
[15:48:57 WARN]: at BattlePass-4.2.8.jar//io.github.battlepass.cache.listener.ConnectionListener.lambda$loadPlayer$1(ConnectionListener.java:64)
[15:48:57 WARN]: at BattlePass-4.2.8.jar//io.github.battlepass.cache.listener.ConnectionListener.lambda$loadPlayer$4(ConnectionListener.java:65)
[15:48:57 WARN]: at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[15:48:57 WARN]: ... 7 more

### How to reproduce

Run the server and let player joins.

**Comment by KPGTB** [comment]
Hey! Are you sure that mysql credentials are correct?
