### ISSUE TITLE
Daily and Weekly quests do not work

### ISSUE THREAD

**Issue by Ekkoy06** [GC-spigot/battle-pass#515]
### Describe the bug

Some quests do not work (shows a barrier on the quests menu)

### How to reproduce

```[14:40:38 WARN]: [BattlePass] Quest: io.github.battlepass.objects.quests.Quest@77eeb037
[14:40:38 WARN]: [BattlePass] Error whilst building menu item for quest: 1 category week-1 name Capitol 1 - Warden Hunter
[14:40:38 WARN]: [BattlePass] Quest Item: ItemStack{WARDEN_SPAWN_EGG x 1, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Warden "},{"italic":false,"color":"white","text":"Hunter"}],"text":""}, lore=[{"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"➥ "},{"italic":false,"color":"white","text":"Omoară "},{"italic":false,"color":"dark_aqua","text":"5 "},{"italic":false,"color":"blue","text":"Wardeni"}],"text":""}, {"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"➥ "},{"italic":false,"color":"white","text":"Progres: "},{"italic":false,"color":"red","text":"%total_progress%"},{"italic":false,"color":"white","text":"/"},{"italic":false,"color":"red","text":"%required_progress%"}],"text":""}, {"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"➥ "},{"italic":false,"color":"yellow","text":"T-XP: "},{"italic":false,"color":"dark_aqua","text":"1.000"}],"text":""}, {"text":""}]}}
[14:40:38 WARN]: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.B" is null
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.pageableItem(WeekMenu.java:63)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.pageableItem(WeekMenu.java:27)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.PageableMenu.drawPageableItems(PageableMenu.java:65)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.redraw(WeekMenu.java:95)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.Menu.show(Menu.java:62)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.QuestOverviewMenu.lambda$pageableItem$4(QuestOverviewMenu.java:69)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.listener.MenuListener.onInventoryClick(MenuListener.java:38)
[14:40:38 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor889.execute(Unknown Source)
[14:40:38 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[14:40:38 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[14:40:38 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:40:38 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[14:40:38 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[14:40:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[14:40:38 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3237)
[14:40:38 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[14:40:38 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[14:40:38 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[14:40:38 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1338)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1315)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1286)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:40:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[14:40:38 WARN]: [BattlePass] Quest: io.github.battlepass.objects.quests.Quest@2e8f761e
[14:40:38 WARN]: [BattlePass] Error whilst building menu item for quest: 2 category week-1 name Capitol 1 - Wither Hunter
[14:40:38 WARN]: [BattlePass] Quest Item: ItemStack{PLAYER_HEAD x 1, SKULL_META:{meta-type=SKULL, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Wither "},{"italic":false,"color":"white","text":"Hunter"}],"text":""}, lore=[{"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"➥ "},{"italic":false,"color":"white","text":"Omoară "},{"italic":false,"color":"dark_aqua","text":"3 "},{"italic":false,"color":"red","text":"Witheri"}],"text":""}, {"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"➥ "},{"italic":false,"color":"white","text":"Progres: "},{"italic":false,"color":"red","text":"%total_progress%"},{"italic":false,"color":"white","text":"/"},{"italic":false,"color":"red","text":"%required_progress%"}],"text":""}, {"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"➥ "},{"italic":false,"color":"yellow","text":"T-XP: "},{"italic":false,"color":"dark_aqua","text":"1.250"}],"text":""}, {"text":""}], Damage=3, skull-owner=CraftPlayerProfile [uniqueId=06960da3-d28b-4b62-9057-a14f4bc1cd3f, name=0.3794280223973806, properties={textures=[{name=textures, value=eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzViNWRiM2ZkNWMyY2IzMjViOGI3MzAyNjZkZWE1MzgzNzBiMzQ4NGM0YWFkZjM4MDhkZDYxNDBmOWM3NDYwMiJ9fX0=, signature=null}]}]}}
[14:40:38 WARN]: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.B" is null
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.pageableItem(WeekMenu.java:63)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.pageableItem(WeekMenu.java:27)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.PageableMenu.drawPageableItems(PageableMenu.java:65)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.redraw(WeekMenu.java:95)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.Menu.show(Menu.java:62)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.QuestOverviewMenu.lambda$pageableItem$4(QuestOverviewMenu.java:69)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.listener.MenuListener.onInventoryClick(MenuListener.java:38)
[14:40:38 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor889.execute(Unknown Source)
[14:40:38 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[14:40:38 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[14:40:38 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:40:38 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[14:40:38 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[14:40:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[14:40:38 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3237)
[14:40:38 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[14:40:38 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[14:40:38 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[14:40:38 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1338)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1315)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1286)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:40:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[14:40:38 WARN]: [BattlePass] Quest: io.github.battlepass.objects.quests.Quest@2d7ac74e
[14:40:38 WARN]: [BattlePass] Error whilst building menu item for quest: 7 category week-1 name Capitol 1 - Timpul
[14:40:38 WARN]: [BattlePass] Quest Item: ItemStack{CLOCK x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Timpul"}],"text":""}, lore=[{"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"➥ "},{"italic":false,"color":"white","text":"Joacă "},{"italic":false,"color":"dark_aqua","text":"3 ore "},{"italic":false,"color":"white","text":"pe"}],"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"server"}],"text":""}, {"text":""}, {"extra":[{"text":"%progress_bar% "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"("},{"italic":false,"color":"green","text":"%percentage_progress%"},{"italic":false,"color":"white","text":")"}],"text":""}, {"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"➥ "},{"italic":false,"color":"yellow","text":"T-XP: "},{"italic":false,"color":"dark_aqua","text":"1.000"}],"text":""}, {"text":""}]}}
[14:40:38 WARN]: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.B" is null
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.pageableItem(WeekMenu.java:63)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.pageableItem(WeekMenu.java:27)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.PageableMenu.drawPageableItems(PageableMenu.java:65)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.redraw(WeekMenu.java:95)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.Menu.show(Menu.java:62)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.QuestOverviewMenu.lambda$pageableItem$4(QuestOverviewMenu.java:69)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.listener.MenuListener.onInventoryClick(MenuListener.java:38)
[14:40:38 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor889.execute(Unknown Source)
[14:40:38 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[14:40:38 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[14:40:38 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:40:38 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[14:40:38 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[14:40:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[14:40:38 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3237)
[14:40:38 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[14:40:38 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[14:40:38 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[14:40:38 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1338)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1315)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1286)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:40:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[14:40:38 WARN]: [BattlePass] Quest: io.github.battlepass.objects.quests.Quest@33190783
[14:40:38 WARN]: [BattlePass] Error whilst building menu item for quest: 9 category week-1 name Capitol 1 - Explorator
[14:40:38 WARN]: [BattlePass] Quest Item: ItemStack{SPYGLASS x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Explorator"}],"text":""}, lore=[{"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"➥ "},{"italic":false,"color":"white","text":"Explorează "},{"italic":false,"color":"dark_aqua","text":"20k "},{"italic":false,"color":"white","text":"metri"}],"text":""}, {"text":""}, {"extra":[{"text":"%progress_bar% "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"("},{"italic":false,"color":"green","text":"%percentage_progress%"},{"italic":false,"color":"white","text":")"}],"text":""}, {"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"➥ "},{"italic":false,"color":"yellow","text":"T-XP: "},{"italic":false,"color":"dark_aqua","text":"1.000"}],"text":""}, {"text":""}]}}
[14:40:38 WARN]: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.B" is null
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.pageableItem(WeekMenu.java:63)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.pageableItem(WeekMenu.java:27)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.PageableMenu.drawPageableItems(PageableMenu.java:65)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.redraw(WeekMenu.java:95)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.Menu.show(Menu.java:62)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.QuestOverviewMenu.lambda$pageableItem$4(QuestOverviewMenu.java:69)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.listener.MenuListener.onInventoryClick(MenuListener.java:38)
[14:40:38 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor889.execute(Unknown Source)
[14:40:38 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[14:40:38 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[14:40:38 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:40:38 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[14:40:38 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[14:40:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[14:40:38 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3237)
[14:40:38 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[14:40:38 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[14:40:38 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[14:40:38 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1338)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1315)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1286)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:40:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[14:40:38 WARN]: [BattlePass] Quest: io.github.battlepass.objects.quests.Quest@33e20bee
[14:40:38 WARN]: [BattlePass] Error whilst building menu item for quest: 10 category week-1 name Capitol 1 - Goana după XP I
[14:40:38 WARN]: [BattlePass] Quest Item: ItemStack{EXPERIENCE_BOTTLE x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Goana după XP"}],"text":""}, lore=[{"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"➥ "},{"italic":false,"color":"white","text":"Adună "},{"italic":false,"color":"dark_aqua","text":"9k "},{"italic":false,"color":"light_purple","text":"XP"}],"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"("},{"italic":false,"color":"light_purple","text":"vanilla XP"},{"italic":false,"color":"white","text":")"}],"text":""}, {"text":""}, {"extra":[{"text":"%progress_bar% "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"("},{"italic":false,"color":"green","text":"%percentage_progress%"},{"italic":false,"color":"white","text":")"}],"text":""}, {"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"➥ "},{"italic":false,"color":"yellow","text":"T-XP: "},{"italic":false,"color":"dark_aqua","text":"1.000"}],"text":""}, {"text":""}]}}
[14:40:38 WARN]: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.B" is null
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.pageableItem(WeekMenu.java:63)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.pageableItem(WeekMenu.java:27)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.PageableMenu.drawPageableItems(PageableMenu.java:65)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.WeekMenu.redraw(WeekMenu.java:95)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.Menu.show(Menu.java:62)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//io.github.battlepass.menus.menus.QuestOverviewMenu.lambda$pageableItem$4(QuestOverviewMenu.java:69)
[14:40:38 WARN]:        at BattlePass-4.3.3.jar//me.hyfe.simplespigot.menu.listener.MenuListener.onInventoryClick(MenuListener.java:38)
[14:40:38 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor889.execute(Unknown Source)
[14:40:38 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[14:40:38 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[14:40:38 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:40:38 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[14:40:38 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[14:40:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[14:40:38 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3237)
[14:40:38 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[14:40:38 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[14:40:38 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[14:40:38 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1338)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1315)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
[14:40:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1286)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[14:40:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:40:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)


### Screenshots / Videos

_No response_

### Server Log

_No response_

**Comment by Ekkoy06** [comment]
![imagine_2024-04-09_154354788](https://github.com/GC-spigot/battle-pass/assets/113153015/4330ab41-2d85-415e-b475-50e601c8570e)

**Comment by KPGTB** [comment]
Duplication of #510
