### ISSUE TITLE
Can you add comma support?

### ISSUE THREAD

**Issue by 1strk0** [GC-spigot/battle-pass#523]
### Describe the feature

`[21:57:54 WARN]: [BattlePass] Task #7363 for BattlePass v4.3.6 generated an exception
java.lang.NumberFormatException: Character , is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
	at java.math.BigDecimal.<init>(BigDecimal.java:586) ~[?:?]
	at java.math.BigDecimal.<init>(BigDecimal.java:471) ~[?:?]
	at java.math.BigDecimal.<init>(BigDecimal.java:900) ~[?:?]
	at net.advancedplugins.bp.impl.actions.external.PlaceholderApiQuests.lambda$placeholderRun$2(PlaceholderApiQuests.java:56) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1285) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1237) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1047) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at java.lang.Thread.run(Thread.java:842) [?:?]
`

please

**Comment by ArabianPandaMC** [comment]
What is meant here is adding support for numbers with formatting that contains commas, such as 12,000 instead of 12000

This is meant for the "placeholderapi_integer_<PLACEHOLDER>" quest type.

**Comment by KPGTB** [comment]
Hey! I added support for "user-friendly" numbers. It will be available in the next update
