### ISSUE TITLE
Kick when claiming battlepass rewards

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/battle-pass#551]
### Describe the bug

players getting kicked when claiming battlepass rewards... on some they do some not

### How to reproduce

come to my server and see? idk if its producable on every server but its just claiming on my server

### Server Log

https://mcpaste.io/cc73ca8968d665f9

**Comment by KPGTB** [comment]
Can you send me configuration files for menus and settings yml file?

**Comment by Rexmen1** [comment]
[08:38:45 ERROR]: Error sending packet clientbound/minecraft:container_set_content (skippable? false)
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:container_set_content'
        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:20) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:26) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection$2.write(Connection.java:756) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at MythicMobs-5.7.0-SNAPSHOT (1).jar/io.lumine.mythic.core.volatilecode.v1_21_R1.packets.VolatileChannelHandler.write(VolatileChannelHandler.java:76) ~[MythicMobs-5.7.0-SNAPSHOT (1).jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at ProtocolLib (22).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib (22).jar:?]
        at ProtocolLib (22).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib (22).jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:513) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at ProtocolLib (22).jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49) ~[ProtocolLib (22).jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Error encoding component minecraft:lore
        at net.minecraft.core.component.DataComponentPatch$1.encodeComponent(DataComponentPatch.java:151) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.core.component.DataComponentPatch$1.encode(DataComponentPatch.java:128) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.core.component.DataComponentPatch$1.encode(DataComponentPatch.java:66) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.world.item.ItemStack$1.encode(ItemStack.java:190) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.world.item.ItemStack$1.encode(ItemStack.java:154) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:413) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:395) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.protocol.game.ClientboundContainerSetContentPacket.write(ClientboundContainerSetContentPacket.java:57) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:38) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:88) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:78) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        ... 45 more
Caused by: java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095) ~[?:?]
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049) ~[?:?]
        at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:412) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:395) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.codec.StreamCodec$4.encode(StreamCodec.java:72) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.core.component.DataComponentPatch$1.encodeComponent(DataComponentPatch.java:149) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.core.component.DataComponentPatch$1.encode(DataComponentPatch.java:128) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.core.component.DataComponentPatch$1.encode(DataComponentPatch.java:66) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.world.item.ItemStack$1.encode(ItemStack.java:190) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.world.item.ItemStack$1.encode(ItemStack.java:154) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:413) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:395) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.protocol.game.ClientboundContainerSetContentPacket.write(ClientboundContainerSetContentPacket.java:57) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:38) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:88) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:78) ~[paper-1.21.jar:1.21-46-2fa5e0e]
        ... 45 more
[08:38:45 WARN]: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:container_set_content'
[08:38:45 WARN]:        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53)
[08:38:45 WARN]:        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:20)
[08:38:45 WARN]:        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:26)
[08:38:45 WARN]:        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12)
[08:38:45 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[08:38:45 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[08:38:45 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[08:38:45 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[08:38:45 WARN]:        at net.minecraft.network.Connection$2.write(Connection.java:756)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[08:38:45 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[08:38:45 WARN]:        at MythicMobs-5.7.0-SNAPSHOT (1).jar//io.lumine.mythic.core.volatilecode.v1_21_R1.packets.VolatileChannelHandler.write(VolatileChannelHandler.java:76)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[08:38:45 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[08:38:45 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[08:38:45 WARN]:        at ProtocolLib (22).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[08:38:45 WARN]:        at ProtocolLib (22).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[08:38:45 WARN]:        at net.minecraft.network.Connection.doSendPacket(Connection.java:513)
[08:38:45 WARN]:        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498)
[08:38:45 WARN]:        at ProtocolLib (22).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49)
[08:38:45 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[08:38:45 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[08:38:45 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[08:38:45 INFO]: (/Bp) rexmen has leveled up to tier 5
[08:38:45 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[08:38:45 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[08:38:45 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[08:38:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[08:38:45 WARN]: Caused by: java.lang.RuntimeException: Error encoding component minecraft:lore
[08:38:45 WARN]:        at net.minecraft.core.component.DataComponentPatch$1.encodeComponent(DataComponentPatch.java:151)
[08:38:45 WARN]:        at net.minecraft.core.component.DataComponentPatch$1.encode(DataComponentPatch.java:128)
[08:38:45 WARN]:        at net.minecraft.core.component.DataComponentPatch$1.encode(DataComponentPatch.java:66)
[08:38:45 WARN]:        at net.minecraft.world.item.ItemStack$1.encode(ItemStack.java:190)
[08:38:45 WARN]:        at net.minecraft.world.item.ItemStack$1.encode(ItemStack.java:154)
[08:38:45 WARN]:        at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:413)
[08:38:45 WARN]:        at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:395)
[08:38:45 WARN]:        at net.minecraft.network.protocol.game.ClientboundContainerSetContentPacket.write(ClientboundContainerSetContentPacket.java:57)
[08:38:45 WARN]:        at net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:38)
[08:38:45 WARN]:        at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:88)
[08:38:45 WARN]:        at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:78)
[08:38:45 WARN]:        ... 45 more
[08:38:45 WARN]: Caused by: java.util.ConcurrentModificationException
[08:38:45 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
[08:38:45 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
[08:38:45 WARN]:        at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:412)
[08:38:45 WARN]:        at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:395)
[08:38:45 WARN]:        at net.minecraft.network.codec.StreamCodec$4.encode(StreamCodec.java:72)
[08:38:45 WARN]:        at net.minecraft.core.component.DataComponentPatch$1.encodeComponent(DataComponentPatch.java:149)
[08:38:45 WARN]:        ... 55 more
[08:38:45 INFO]: rexmen lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:container_set_content'

**Comment by Rexmen1** [comment]
[archive-2024-07-07T083938Z.tar.gz](https://github.com/user-attachments/files/16118587/archive-2024-07-07T083938Z.tar.gz)

**Comment by KPGTB** [comment]
Hey! It doesn't look like a bug caused by our plugin. Error says about `ProtocolLib` and `MythicMobs`. I also tested files which you sent, but I couldn't reproduce that error.
