### ISSUE TITLE
Plugin not loading on 1.21

### ISSUE THREAD

**Issue by xProMDFKx** [GC-spigot/battle-pass#573]
### Describe the bug

It's just not loading, i am using latest battlepass plugin (also i used some versions before the latest updated and they did not save the player progress on restart)

### How to reproduce

Just update to latest jar

### Screenshots / Videos

[03:55:49 ERROR]: Error occurred while enabling BattlePass v4.6.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at BattlePass-4.6.2.jar/net.advancedplugins.bp.impl.actions.ActionRegistry.<init>(ActionRegistry.java:62) ~[BattlePass-4.6.2.jar:?]
        at BattlePass-4.6.2.jar/io.github.battlepass.BattlePlugin.load(BattlePlugin.java:305) ~[BattlePass-4.6.2.jar:?]
        at BattlePass-4.6.2.jar/io.github.battlepass.BattlePlugin.onEnable(BattlePlugin.java:133) ~[BattlePass-4.6.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-124-df3b654]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Invalid namespace. Must be [a-z0-9._-]: PlayerBlockTracker
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:86) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at BattlePass-4.6.2.jar/net.advancedplugins.bp.impl.actions.blocktracker.Tracker.<clinit>(Tracker.java:14) ~[BattlePass-4.6.2.jar:?]
        ... 15 more
[03:55:49 INFO]: [BattlePass] Disabling BattlePass v4.6.2
[03:55:49 ERROR]: Error occurred while disabling BattlePass v4.6.2
java.lang.NullPointerException: Cannot invoke "net.advancedplugins.bp.impl.actions.ActionRegistry.unload()" because "this.g" is null
        at BattlePass-4.6.2.jar/io.github.battlepass.BattlePlugin.unload(BattlePlugin.java:367) ~[BattlePass-4.6.2.jar:?]
        at BattlePass-4.6.2.jar/io.github.battlepass.BattlePlugin.onDisable(BattlePlugin.java:154) ~[BattlePass-4.6.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.jar:1.21-124-df3b654]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.jar:1.21-124-df3b654]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Server Log

https://mcpaste.io/503a43f53242d227

**Comment by KPGTB** [comment]
Duplication of #572
