### ISSUE TITLE
Spam after new update

### ISSUE THREAD

**Issue by bobhenl** [GC-spigot/battle-pass#578]
### Describe the bug

Hello, I got this error when someone join:
```yml
3:43:24 INFO]: xchengnlx issued server command: /spawn
[13:43:24 WARN]: [BattlePass] Task #1909 for BattlePass v4.6.4 generated an exception
java.lang.NullPointerException: Cannot invoke "net.advancedplugins.bp.impl.actions.objects.variable.Variable.getConditions()" because "<parameter2>" is null
        at BattlePass-4.6.4.jar/net.advancedplugins.bp.impl.actions.objects.variable.ExecutableActionResult.areSubRootsValid(ExecutableActionResult.java:125) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/net.advancedplugins.bp.impl.actions.objects.variable.ExecutableActionResult.isEligible(ExecutableActionResult.java:93) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.proceed(QuestValidationStep.java:113) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.processCompletion(QuestValidationStep.java:94) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/io.github.battlepass.quests.workers.pipeline.QuestPipeline.handle(QuestPipeline.java:64) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/io.github.battlepass.quests.ActionsHandler.onAction(ActionsHandler.java:12) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/net.advancedplugins.bp.impl.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:39) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/net.advancedplugins.bp.impl.actions.internal.PlayTimeQuest.lambda$run$0(PlayTimeQuest.java:22) ~[BattlePass-4.6.4.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2280-930003b]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1762) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2280-930003b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

If there's configuration wrong, how can I discover where or so?

### How to reproduce

I don't know, just someone join

**Comment by KPGTB** [comment]
Duplication of #576 
(Check that issue to get more info about this problem)
