### ISSUE TITLE
NBTAPI error console

### ISSUE THREAD

**Issue by GG-MD** [GC-spigot/battle-pass#594]
### Describe the bug

There's also no progress 

`> ver BattlePass
[08:56:00 INFO]: BattlePass version 4.6.12
[08:56:01 INFO]: [local] Nor41k: да
> ver
[08:56:02 INFO]: Checking version, please wait...
[08:56:03 INFO]: Current Purpur Version: 1.21.1-2299-5c0d2f7 (MC: 1.21.1)*
* You are running the latest version`

```
[08:34:58] [Server thread/ERROR]: Could not pass event PlayerItemConsumeEvent to BattlePass v4.6.12
java.lang.NoClassDefFoundError: libs/de/tr7zw/changeme/nbtapi/utils/MinecraftVersion
	at BattlePass-4.6.12.jar/net.advancedplugins.bp.impl.actions.internal.ConsumeQuest.onItemConsume(ConsumeQuest.java:30) ~[BattlePass-4.6.12.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor870.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2299-5c0d2f7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.entity.LivingEntity.completeUsingItem(LivingEntity.java:4222) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.level.ServerPlayer.completeUsingItem(ServerPlayer.java:2079) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.world.entity.LivingEntity.updateUsingItem(LivingEntity.java:4079) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.level.ServerPlayer.updateUsingItem(ServerPlayer.java:2779) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.world.entity.LivingEntity.updatingUsingItem(LivingEntity.java:4059) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3227) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.world.entity.player.Player.tick(Player.java:317) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:854) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:360) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.network.Connection.tick(Connection.java:647) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1861) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: libs.de.tr7zw.changeme.nbtapi.utils.MinecraftVersion
	... 25 more
```

### How to reproduce

—

**Comment by GG-MD** [comment]
@GC-spigot help me pls

**Comment by GG-MD** [comment]
https://spark.lucko.me/s3FSrZnaap
@GC-spigot !!!!!!!

**Comment by KPGTB** [comment]
Duplication of #593
